### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by uma-sethuraman**
Added updated compiling and testing instructions and cleaned up the formatting

### CODE REVIEW

**Comment by JorySchossau** [comment]
Can you integrate the new build instructions (stupidly I hid them in `code/build/readme.md`)?
The system is built on cmake and being able to use the cmake gui (ccmake) to easily change between genomes.

**Comment by uma-sethuraman** [comment]
I integrated the new build instructions into the readme and deleted the readme file from `code/build`. I also updated the catch.hpp file in this branch because there were merge conflicts in the catch.hpp file in master.

**Comment by JorySchossau** [comment]
Looking good - can you verify that Bench builds as expected now? Good catch on the lingering typedef error.

**Comment by uma-sethuraman** [comment]
I ran the benchmarking again, and Bench does build as expected now! Thanks for fixing the issue!

**Pull request merged**
